// Code generated by mockery v1.0.0. DO NOT EDIT.

package authentication

import message "github.com/hyperscale/hyperpush/pkg/hyperpush/message"
import mock "github.com/stretchr/testify/mock"

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: accessToken
func (_m *MockProvider) Authenticate(accessToken string) (*User, message.ErrorInterface) {
	ret := _m.Called(accessToken)

	var r0 *User
	if rf, ok := ret.Get(0).(func(string) *User); ok {
		r0 = rf(accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*User)
		}
	}

	var r1 message.ErrorInterface
	if rf, ok := ret.Get(1).(func(string) message.ErrorInterface); ok {
		r1 = rf(accessToken)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(message.ErrorInterface)
		}
	}

	return r0, r1
}
