// Code generated by mockery v1.0.0. DO NOT EDIT.

package push

import authentication "github.com/hyperscale/hyperpush/pkg/hyperpush/authentication"
import http "net/http"
import message "github.com/hyperscale/hyperpush/pkg/hyperpush/message"
import mock "github.com/stretchr/testify/mock"

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: token, client
func (_m *MockServer) Authenticate(token string, client *Client) {
	_m.Called(token, client)
}

// JoinChannel provides a mock function with given fields: ID, client
func (_m *MockServer) JoinChannel(ID string, client *Client) {
	_m.Called(ID, client)
}

// Leave provides a mock function with given fields: client
func (_m *MockServer) Leave(client *Client) {
	_m.Called(client)
}

// LeaveChannel provides a mock function with given fields: ID, client
func (_m *MockServer) LeaveChannel(ID string, client *Client) {
	_m.Called(ID, client)
}

// Listen provides a mock function with given fields:
func (_m *MockServer) Listen() {
	_m.Called()
}

// Publish provides a mock function with given fields: _a0
func (_m *MockServer) Publish(_a0 *message.Event) {
	_m.Called(_a0)
}

// ServeHTTP provides a mock function with given fields: w, r
func (_m *MockServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// SetAuthenticationProvider provides a mock function with given fields: provider
func (_m *MockServer) SetAuthenticationProvider(provider authentication.Provider) {
	_m.Called(provider)
}
