// Code generated by mockery v1.0.0. DO NOT EDIT.

package push

import authentication "github.com/hyperscale/hyperpush/pkg/hyperpush/authentication"
import mock "github.com/stretchr/testify/mock"
import packets "github.com/hyperscale/hyperpush/pkg/hyperpush/mqtt/packets"

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields: packet, client
func (_m *MockServer) Authenticate(packet *packets.ConnectPacket, client *Client) {
	_m.Called(packet, client)
}

// JoinTopic provides a mock function with given fields: packet, client
func (_m *MockServer) JoinTopic(packet *packets.SubscribePacket, client *Client) {
	_m.Called(packet, client)
}

// Leave provides a mock function with given fields: client
func (_m *MockServer) Leave(client *Client) {
	_m.Called(client)
}

// LeaveTopic provides a mock function with given fields: packet, client
func (_m *MockServer) LeaveTopic(packet *packets.UnsubscribePacket, client *Client) {
	_m.Called(packet, client)
}

// ListenAndServe provides a mock function with given fields:
func (_m *MockServer) ListenAndServe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Publish provides a mock function with given fields: message
func (_m *MockServer) Publish(message *packets.PublishPacket) {
	_m.Called(message)
}

// SetAuthenticationProvider provides a mock function with given fields: provider
func (_m *MockServer) SetAuthenticationProvider(provider authentication.Provider) {
	_m.Called(provider)
}
